### ISSUE TITLE
TypeError: null is not an object (evaluating 'JailMonkey.isDevelopmentSettingsMode')] on ANDROID

### ISSUE THREAD

**Issue by mayran-aragao** [GantMan/jail-monkey#106]
[Unhandled promise rejection: TypeError: null is not an object (evaluating 'JailMonkey.isDevelopmentSettingsMode')]
at node_modules/jail-monkey/jailmonkey.js:16:8 in isDevelopmentSettingsMode
at src/screens/Home/HomeScreen.js:66:26 in <anonymous>
at src/screens/Home/HomeScreen.js:65:9 in <anonymous>
at src/screens/Home/HomeScreen.js:65:8 in useEffect$argument_0
at node_modules/@react-navigation/core/src/useSyncState.tsx:39:22 in React.useCallback$argument_0
at node_modules/@react-navigation/core/src/useNavigationBuilder.tsx:309:21 in React.useCallback$argument_0
at node_modules/@react-navigation/core/src/useOnAction.tsx:105:20 in React.useCallback$argument_0
at node_modules/@react-navigation/core/src/useNavigationHelpers.tsx:43:30 in dispatch
at node_modules/@react-navigation/core/src/useNavigationCache.tsx:91:10 in dispatch
at node_modules/@react-navigation/core/src/useNavigationCache.tsx:122:22 in withStack$argument_0
at node_modules/@react-navigation/core/src/useNavigationCache.tsx:109:18 in withStack
at node_modules/@react-navigation/core/src/useNavigationCache.tsx:120:21 in acc.name
at src/screens/Preload/PreloadScreen.js:21:19 in checkLogin

I already did manual link, import, add the package, but nothing works

**Comment by mayran-aragao** [comment]
"Solved"
the problem was my react native version. I tried the 0.64.1 version and it works fine.
